import { useEffect, useState, type FormEvent } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { Wordmark } from "@/components/Header";
import { EyeIcon, EyeOffIcon, KeyIcon, LockIcon, QrIcon, ShieldIcon, UserIcon } from "@/components/icons";
import { LocationFields, type LocationValue } from "@/components/LocationFields";
import { PhoneCountryInput } from "@/components/PhoneCountryInput";
import { QrScannerModal } from "@/components/QrScannerModal";
import { completeSignup, getPortalSession, loginPortal, sendSignupOtp, type PortalRole } from "@/lib/auth";

function AuthShell({ title, lede, children }: { title: string; lede: string; children: React.ReactNode }) {
  useEffect(()=>{const previous=document.title;document.title=`${title} — ARANCH PASS`;let meta=document.querySelector<HTMLMetaElement>('meta[name="robots"]');const made=!meta;if(!meta){meta=document.createElement("meta");meta.name="robots";document.head.appendChild(meta)}const old=meta.content;meta.content="noindex,nofollow";return()=>{document.title=previous;if(made)meta?.remove();else if(meta)meta.content=old}},[title]);
  return <div className="min-h-screen bg-paper text-ink"><header className="border-b border-line px-5 py-5"><div className="mx-auto flex max-w-[1160px] items-center justify-between"><Link to="/"><Wordmark tone="violet" /></Link><Link to="/customer" className="mono text-[10px] tracking-[.12em] text-violet uppercase">Customer portal</Link></div></header><main className="mx-auto grid max-w-[1160px] gap-10 px-5 py-12 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:py-20"><div><p className="label text-violet">Secure portal</p><h1 className="font-display t-5 mt-5 max-w-[12ch] font-bold text-deepviolet">{title}</h1><p className="mt-5 max-w-[45ch] text-[16px] leading-relaxed text-ink/70">{lede}</p><div className="mt-8 grid max-w-[500px] gap-3 sm:grid-cols-3">{[[ShieldIcon,"Role checked"],[LockIcon,"Private session"],[QrIcon,"Customer remains public"]].map(([Icon,label])=>{const C=Icon as typeof ShieldIcon;return <div key={String(label)} className="clip-corner hairline bg-ivory p-4"><C className="text-violet"/><p className="mt-3 text-[12px] font-semibold text-deepviolet">{String(label)}</p></div>})}</div></div><div className="clip-corner hairline bg-white p-6 shadow-[0_28px_70px_-45px_rgba(46,7,89,.45)] sm:p-8">{children}</div></main></div>;
}

const field = "hairline w-full bg-paper py-3.5 pr-4 pl-11 text-[15px] text-ink outline-none focus:border-violet";

export function LoginPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const existing = getPortalSession();
  const [identifier, setIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  if (existing) return <Navigate to={existing.role === "ceo" ? "/ceo" : "/provider"} replace />;

  const submit = async (event: FormEvent) => {
    event.preventDefault();setBusy(true);setError("");
    try { const session=await loginPortal(identifier,password); const requested=(location.state as {from?:string}|null)?.from; navigate(requested || (session.role==="ceo"?"/ceo":"/provider"),{replace:true}); }
    catch(e){setError(e instanceof Error?e.message:"Login failed.");} finally{setBusy(false)}
  };

  return <AuthShell title="Welcome back." lede="Sign in with your phone number or username to continue to your ARANCH PASS workspace."><form onSubmit={submit}><p className="label text-violet">Login</p><h2 className="font-display mt-2 text-2xl font-bold text-deepviolet">Access your portal</h2><label className="mt-6 block text-[12px] font-bold text-deepviolet" htmlFor="identifier">Phone number or username</label><div className="relative mt-2"><UserIcon className="absolute top-1/2 left-4 -translate-y-1/2 text-violet"/><input id="identifier" value={identifier} onChange={e=>setIdentifier(e.target.value)} className={field} autoComplete="username" required /></div><label className="mt-5 block text-[12px] font-bold text-deepviolet" htmlFor="password">Password</label><div className="relative mt-2"><LockIcon className="absolute top-1/2 left-4 -translate-y-1/2 text-violet"/><input id="password" type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className={`${field} pr-12`} autoComplete="current-password" required /><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute top-1/2 right-3 grid h-9 w-9 -translate-y-1/2 place-items-center text-violet" aria-label={showPassword?"Hide password":"Show password"} aria-pressed={showPassword}>{showPassword?<EyeOffIcon/>:<EyeIcon/>}</button></div>{error&&<p role="alert" className="mt-4 text-[13px] text-red-700">{error}</p>}<button disabled={busy} className="clip-corner-sm mt-6 w-full bg-saffron px-5 py-4 text-[12px] font-extrabold tracking-[.1em] text-plum uppercase disabled:opacity-60">{busy?"Checking…":"Login"}</button><p className="mt-5 text-center text-[13px] text-muted">New provider? <Link className="font-bold text-violet underline" to="/signup">Create an account</Link></p><div className="mt-6 border-t border-line pt-5"><p className="mono text-[10px] text-muted uppercase">Local demo credentials</p><div className="mono mt-3 grid gap-2 text-[11px] text-deepviolet sm:grid-cols-2"><button type="button" onClick={()=>{setIdentifier("provider123");setPassword("provider123")}} className="hairline p-3 text-left">provider123 / provider123</button><button type="button" onClick={()=>{setIdentifier("admin123");setPassword("admin123")}} className="hairline p-3 text-left">admin123 / admin123</button></div></div></form></AuthShell>;
}

export function SignupPage() {
  const navigate=useNavigate();const [sent,setSent]=useState(false);const [phone,setPhone]=useState("");const [username,setUsername]=useState("");const [otp,setOtp]=useState("");const [password,setPassword]=useState("");const [showPassword,setShowPassword]=useState(false);const [location,setLocation]=useState<LocationValue>({pincode:"",city:"",district:"",state:"",postOffice:""});const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  const send=async()=>{setBusy(true);setError("");try{const r=await sendSignupOtp(phone);setSent(true);setNotice(r.demoOtp?"Demo OTP: 123456":"OTP sent to your phone.")}catch(e){setError(e instanceof Error?e.message:"Could not send OTP.")}finally{setBusy(false)}};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!sent){await send();return}setBusy(true);setError("");try{await completeSignup({phone,username,otp,password,location});navigate("/provider",{replace:true})}catch(err){setError(err instanceof Error?err.message:"Signup failed.")}finally{setBusy(false)}};
  return <AuthShell title="Provider signup, verified by phone." lede="Customer access stays public. Accounts are created only for providers and authorised team members. Production signup uses Supabase phone OTP and creates a provider profile after verification."><form onSubmit={submit}><p className="label text-violet">Provider signup</p><h2 className="font-display mt-2 text-2xl font-bold text-deepviolet">Create your account</h2><label className="mt-6 block text-[12px] font-bold text-deepviolet" htmlFor="phone">Mobile phone number</label><div className="mt-2"><PhoneCountryInput id="phone" value={phone} onChange={setPhone} disabled={sent} required /></div>{!sent&&<button type="button" onClick={()=>void send()} disabled={busy} className="clip-corner-sm mt-5 w-full bg-saffron px-5 py-4 text-[12px] font-extrabold text-plum uppercase disabled:opacity-60">{busy?"Sending…":"Send OTP"}</button>}{sent&&<><label className="mt-5 block text-[12px] font-bold text-deepviolet" htmlFor="username">Username</label><div className="relative mt-2"><UserIcon className="absolute top-1/2 left-4 -translate-y-1/2 text-violet"/><input id="username" value={username} onChange={e=>setUsername(e.target.value)} className={field} autoComplete="username" required/></div><label className="mt-5 block text-[12px] font-bold text-deepviolet" htmlFor="otp">OTP</label><div className="relative mt-2"><KeyIcon className="absolute top-1/2 left-4 -translate-y-1/2 text-violet"/><input id="otp" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} className={field} inputMode="numeric" autoComplete="one-time-code" required/></div><label className="mt-5 block text-[12px] font-bold text-deepviolet" htmlFor="new-password">Password</label><div className="relative mt-2"><LockIcon className="absolute top-1/2 left-4 -translate-y-1/2 text-violet"/><input id="new-password" type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className={`${field} pr-12`} autoComplete="new-password" minLength={8} required/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute top-1/2 right-3 grid h-9 w-9 -translate-y-1/2 place-items-center text-violet" aria-label={showPassword?"Hide password":"Show password"} aria-pressed={showPassword}>{showPassword?<EyeOffIcon/>:<EyeIcon/>}</button></div><LocationFields value={location} onChange={setLocation} required/><button disabled={busy} className="clip-corner-sm mt-6 w-full bg-saffron px-5 py-4 text-[12px] font-extrabold text-plum uppercase disabled:opacity-60">{busy?"Creating…":"Verify & create provider account"}</button></>}{notice&&<p className="mt-4 text-[13px] text-violet">{notice}</p>}{error&&<p role="alert" className="mt-4 text-[13px] text-red-700">{error}</p>}<p className="mt-5 text-center text-[13px] text-muted">Already registered? <Link className="font-bold text-violet underline" to="/login">Login</Link></p></form></AuthShell>;
}

function assetCodeFromQr(raw: string) {
  const match = raw.toUpperCase().match(/AP-[A-Z0-9]{5,14}/);
  return match?.[0] || raw.trim().toUpperCase();
}

export function CustomerPortalPage() {
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const navigate = useNavigate();
  useEffect(()=>{const previous=document.title;document.title="Customer portal — ARANCH PASS";let meta=document.querySelector<HTMLMetaElement>('meta[name="robots"]');const made=!meta;if(!meta){meta=document.createElement("meta");meta.name="robots";document.head.appendChild(meta)}const old=meta.content;meta.content="noindex,nofollow";return()=>{document.title=previous;if(made)meta?.remove();else if(meta)meta.content=old}},[]);
  const openCode = (value: string) => {
    const parsed = assetCodeFromQr(value);
    if (!/^AP-[A-Z0-9]{5,14}$/.test(parsed)) { setError("This does not look like a valid ARANCH PASS code or QR value."); return; }
    setCode(parsed);setError("");navigate(`/customer-demo?code=${encodeURIComponent(parsed)}`);
  };
  return <div className="min-h-screen bg-paper"><header className="border-b border-line px-5 py-5"><div className="mx-auto flex max-w-[1100px] items-center justify-between"><Link to="/"><Wordmark tone="violet"/></Link><Link to="/login" className="mono text-[10px] text-violet uppercase">Provider login</Link></div></header><main className="mx-auto max-w-[900px] px-5 py-14 text-center sm:py-24"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-saffron text-plum"><QrIcon width={30} height={30}/></div><p className="label mt-7 text-violet">Customer portal · no signup required</p><h1 className="font-display t-5 mt-4 font-bold text-deepviolet">Scan a pass or enter its code.</h1><p className="mx-auto mt-5 max-w-[58ch] leading-relaxed text-ink/70">Use the camera to scan the physical ARANCH PASS QR code. If camera access is unavailable, upload a QR image or enter the short asset code manually.</p><div className="mx-auto mt-9 grid max-w-[680px] gap-3 sm:grid-cols-[auto_1fr]"><QrScannerModal onResult={openCode}/><form onSubmit={e=>{e.preventDefault();openCode(code)}} className="flex min-w-0 flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="asset-code">Asset code</label><input id="asset-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} className="hairline min-w-0 flex-1 bg-white px-5 py-4 font-mono text-deepviolet uppercase" placeholder="AP-7K3M9"/><button className="clip-corner-sm bg-deepviolet px-6 py-4 text-[12px] font-bold text-ivory uppercase">Check code</button></form></div>{error&&<p role="alert" className="mx-auto mt-4 max-w-[680px] border border-red-300 bg-red-50 px-4 py-3 text-[13px] text-red-700">{error}</p>}<div className="mx-auto mt-8 grid max-w-[680px] gap-3 text-left sm:grid-cols-3">{[["01","Camera opens only after you tap Scan QR code"],["02","QR detection runs on the device"],["03","No customer account is required"]].map(([n,t])=><div key={n} className="clip-corner hairline bg-ivory p-4"><span className="mono text-[10px] text-saffron">{n}</span><p className="mt-2 text-[12px] leading-relaxed text-ink/70">{t}</p></div>)}</div><p className="mono mt-6 text-[10px] text-muted">DEMO ROUTE · A PRODUCTION PUBLIC LOOKUP API IS NOT CONNECTED YET.</p></main></div>;
}

export function RequirePortalRole({role,children}:{role:PortalRole;children:React.ReactNode}){const session=getPortalSession();const location=useLocation();if(!session||session.role!==role)return <Navigate to="/login" replace state={{from:location.pathname}}/>;return children}
